### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by luob1215**
#10

### CODE REVIEW

**Comment by rustbot-yn** [comment]
@luob1215: no appropriate reviewer found, use r? to override

**Comment by rustbot-yn** [comment]
Failed to set assignee to `to`: invalid assignee

> **Note**: Only org members, users with write permissions, or people who have commented on the PR may be assigned.

**Comment by rustbot-yn** [comment]
**Error**: This team (`test`) does not exist in the team repository.

Please file an issue on GitHub at [triagebot](https://github.com/rust-lang/triagebot) if there's a problem with this bot, or reach out on [#t-infra](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra) on Zulip.

**Comment by luob1215** [comment]
Please r? @yn-bot can you review?

**Pull request merged**
