### PR TITLE
update triagebot.toml

### PR DESCRIPTION
**Pull request by luob1215**
#11 update triagebot.toml

### CODE REVIEW

**Comment by rustbot-yn** [comment]
@luob1215: no appropriate reviewer found, use r? to override

**Comment by rustbot-yn** [comment]
Failed to set assignee to `to`: invalid assignee

> **Note**: Only org members, users with write permissions, or people who have commented on the PR may be assigned.

**Comment by luob1215** [comment]
r?

**Comment by rustbot-yn** [comment]
**Error**: Parsing assign command in [comment](https://github.com/KuPayIo/demo/pull/12#issuecomment-1431116891) failed: ...'' | error: specify user to assign to at >| ''...

Please file an issue on GitHub at [triagebot](https://github.com/rust-lang/triagebot) if there's a problem with this bot, or reach out on [#t-infra](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra) on Zulip.

**Pull request merged**
